### ISSUE TITLE
expv gives wrong results for a specific matrix

### ISSUE THREAD

**Issue by Roger-luo** [SciML/ExponentialUtilities.jl#52]
using this 55x55 matrix with `expv` gives wrong results

```julia
cols = [1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 28, 28, 28, 28, 29, 29, 29, 29, 30, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 32, 32, 32, 32, 33, 33, 33, 33, 33, 34, 34, 34, 34, 34, 35, 35, 35, 35, 35, 35, 35, 36, 36, 36, 36, 36, 36, 36, 37, 37, 37, 37, 37, 37, 38, 38, 38, 38, 38, 38, 39, 39, 39, 39, 39, 39, 40, 40, 40, 40, 40, 40, 41, 41, 41, 41, 41, 42, 42, 42, 42, 42, 43, 43, 43, 43, 43, 43, 44, 44, 44, 44, 44, 45, 45, 45, 45, 46, 46, 46, 46, 46, 47, 47, 47, 47, 47, 48, 48, 48, 48, 48, 48, 48, 49, 49, 49, 49, 49, 49, 50, 50, 50, 50, 50, 51, 51, 51, 51, 51, 52, 52, 52, 52, 52, 53, 53, 53, 53, 53, 53, 54, 54, 54, 54, 54, 55, 55, 55, 55, 55]
rows = [2, 3, 4, 6, 9, 14, 22, 35, 1, 5, 7, 10, 15, 23, 36, 1, 8, 11, 16, 24, 37, 1, 5, 12, 17, 25, 38, 2, 4, 5, 13, 18, 26, 39, 1, 7, 8, 19, 27, 40, 2, 6, 7, 20, 28, 41, 3, 6, 8, 21, 29, 42, 1, 10, 11, 12, 30, 43, 2, 9, 10, 13, 31, 44, 3, 9, 11, 32, 45, 4, 9, 12, 13, 33, 46, 5, 10, 12, 13, 34, 47, 1, 15, 16, 17, 19, 48, 2, 14, 15, 18, 20, 49, 3, 14, 16, 21, 50, 4, 14, 17, 18, 51, 5, 15, 17, 18, 52, 6, 14, 19, 20, 21, 53, 7, 15, 19, 20, 54, 8, 16, 19, 21, 55, 1, 23, 24, 25, 27, 30, 2, 22, 23, 26, 28, 31, 3, 22, 24, 29, 32, 4, 22, 25, 26, 33, 5, 23, 25, 26, 34, 6, 22, 27, 28, 29, 7, 23, 27, 28, 8, 24, 27, 29, 9, 22, 30, 31, 32, 33, 10, 23, 30, 31, 34, 11, 24, 30, 32, 12, 25, 30, 33, 34, 13, 26, 31, 33, 34, 1, 36, 37, 38, 40, 43, 48, 2, 35, 36, 39, 41, 44, 49, 3, 35, 37, 42, 45, 50, 4, 35, 38, 39, 46, 51, 5, 36, 38, 39, 47, 52, 6, 35, 40, 41, 42, 53, 7, 36, 40, 41, 54, 8, 37, 40, 42, 55, 9, 35, 43, 44, 45, 46, 10, 36, 43, 44, 47, 11, 37, 43, 45, 12, 38, 43, 46, 47, 13, 39, 44, 46, 47, 14, 35, 48, 49, 50, 51, 53, 15, 36, 48, 49, 52, 54, 16, 37, 48, 50, 55, 17, 38, 48, 51, 52, 18, 39, 49, 51, 52, 19, 40, 48, 53, 54, 55, 20, 41, 49, 53, 54, 21, 42, 50, 53, 55]
vals = [12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0]
```

copy-paste the above code to REPL, and then

```julia
julia> M = sparse(rows, cols, vals)

julia> t = 0.9; st = rand(55);

julia> expv(-im*t, Matrix(H), st) ≈ exp(-im*t*Matrix(H)) * st
false
```

the error increases with `t`, thus I'm guessing there are something wrong with the convergence criteria?

**Comment by Roger-luo** [comment]
meanwhile, this code copied from Expokit (I think it's abandoned now) works,

replace the above `expv` with the following `expmv`

```julia
using LinearAlgebra
export expmv, expmv!
function default_anorm(A)
    try
        opnorm(A, Inf)
    catch err
        if err isa MethodError
            @warn "opnorm($(typeof(A)), Inf) is not defined, fall back to using `anorm = 1.0`.
To suppress this warning, please specify the `anorm` keyword manually."
            1.0
        else
            throw(err)
        end
    end
end
"""
    expmv{T}(t, A, vec; [tol], [m], [norm], [anorm])
Calculate matrix exponential acting on some vector, ``w = e^{tA}v``,
using the Krylov subspace approximation.
See R.B. Sidje, ACM Trans. Math. Softw., 24(1):130-156, 1998
and http://www.maths.uq.edu.au/expokit
"""
function expmv( t::Number,
                   A, vec::Vector{T};
                   tol::Real=1e-7,
                   m::Int=min(30, size(A, 1)),
                   norm=LinearAlgebra.norm, anorm=default_anorm(A)) where {T}
    result = convert(Vector{promote_type(eltype(A), T, typeof(t))}, copy(vec))
    expmv!(t, A, result; tol=tol, m=m, norm=norm, anorm=anorm)
    return result
end
expmv!( t::Number,
           A, vec::Vector{T};
           tol::Real=1e-7,
           m::Int=min(30,size(A,1)),
           norm=LinearAlgebra.norm, anorm=default_anorm(A)) where {T} = expmv!(vec, t, A, vec; tol=tol, m=m, norm=norm, anorm=anorm)
function expmv!(w::Vector{T}, t::Number, A, vec::Vector{T};
                   tol::Real=1e-7, m::Int=min(30,size(A,1)), norm=LinearAlgebra.norm, anorm=default_anorm(A)) where {T}
    if size(vec,1) != size(A,2)
        error("dimension mismatch")
    end
    # safety factors
    gamma = 0.9
    delta = 1.2
    btol = 1e-7     # tolerance for "happy-breakdown"
    maxiter = 10    # max number of time-step refinements
    rndoff= anorm*eps()
    # estimate first time-step and round to two significant digits
    beta = norm(vec)
    r = 1/m
    fact = (((m+1)/exp(1.0))^(m+1))*sqrt(2.0*pi*(m+1))
    tau = (1.0/anorm)*((fact*tol)/(4.0*beta*anorm))^r
    tau = round(tau, sigdigits=2)
    # storage for Krylov subspace vectors
    vm = Array{typeof(w)}(undef,m+1)
    for i=1:m+1
        vm[i]=similar(w)
    end
    hm = zeros(T,m+2,m+2)
    tf = abs(t)
    tsgn = sign(t)
    tk = zero(tf)
    copyto!(w, vec)
    p = similar(w)
    mx = m
    while tk < tf
        tau = min(tf-tk, tau)
        # Arnoldi procedure
        # vm[1] = v/beta
        rmul!(copyto!(vm[1],w),1/beta)
        mx = m
        for j=1:m
            # p[:] = A*vm[j]
            mul!(p, A, vm[j])
            for i=1:j
                hm[i,j] = dot(vm[i], p)
                # p[:] = p - hm[i,j]*vm[i]
                p = axpy!(-hm[i,j], vm[i], p)
            end
            s = norm(p)
            if s < btol # happy-breakdown
                tau = tf - tk
                err_loc = btol
                # F = expm(tsgn*tau*hm[1:j,1:j])
                # F = expm!(scale(tsgn*tau,view(hm,1:j,1:j)))
                F = LinearAlgebra.exp!(tsgn*tau*view(hm,1:j,1:j))
                fill!(w, zero(T))
                for k=1:j
                    # w[:] = w + beta*vm[k]*F[k,1]
                    w = axpy!(beta*F[k,1], vm[k], w)
                end
                mx = j
                break
            end
            hm[j+1,j] = s
            # vm[j+1] = p/hm[j+1,j]
            rmul!(copyto!(vm[j+1],p),1/hm[j+1,j])
        end
        hm[m+2,m+1] = one(T)
        (mx != m) || (avnorm = norm(mul!(p,A,vm[m+1])))
        # propagate using adaptive step size
        iter = 1
        while (iter < maxiter) && (mx == m)
            # F = expm(tsgn*tau*hm)
            # F = expm!(scale(tsgn*tau,hm))
            F = LinearAlgebra.exp!(tsgn*tau*hm)
            # local error estimation
            err1 = abs( beta*F[m+1,1] )
            err2 = abs( beta*F[m+2,1] * avnorm )
            if err1 > 10*err2	# err1 >> err2
                err_loc = err2
                r = 1/m
            elseif err1 > err2
                err_loc = (err1*err2)/(err1-err2)
                r = 1/m
            else
                err_loc = err1
                r = 1/(m-1)
            end
            # time-step sufficient?
            if err_loc <= delta * tau * (tau*tol/err_loc)^r
                fill!(w, zero(T))
                for k=1:m+1
                    # w[:] = w + beta*vm[k]*F[k,1]
                    w = axpy!(beta*F[k,1], vm[k], w)
                end
                break
            end
            tau = gamma * tau * (tau*tol/err_loc)^r # estimate new time-step
            tau = round(tau, sigdigits=2) # round to 2 signiﬁcant digits
                                 # to prevent numerical noise
            iter = iter + 1
        end
        if iter == maxiter
            # TODO, here an exception should be thrown, but which?
            error("Number of iterations exceeded $(maxiter). Requested tolerance might be to high.")
        end
        beta = norm(w)
        tk = tk + tau
        tau = gamma * tau * (tau*tol/err_loc)^r # estimate new time-step
        tau = round(tau, sigdigits=2) # round to 2 signiﬁcant digits
                             # to prevent numerical noise
        err_loc = max(err_loc,rndoff)
        fill!(hm, zero(T))
    end
    return w
end # expmv!
```

**Comment by Roger-luo** [comment]
OK after some investigate and comparision with the implementation in other languages (such as scipy: https://github.com/scipy/scipy/blob/v1.6.0/scipy/sparse/linalg/_expm_multiply.py#L516), it seems `expv_timestep` is the actual conventional `expmv` implementation instead of `expv`, I'm wondering if someone (maybe @ChrisRackauckas ? ) could explain a bit why the name convention has such a difference? I was thinking `expv` is the conventional `expmv` function from MATLAB etc. (e.g the implementation in Expokit)

**Comment by ChrisRackauckas** [comment]
Yeah I'm not sure. A lot of work was put in to ensure numerically accuracy and we fixed a lot of cases ExpoKit couldn't handle (you can see the old PRs here and in OrdinaryDiffEq for that with pictures), but someone would have to really dig in for this one. Is it very ill-conditioned, or is it some other kind of behavior?

**Comment by Roger-luo** [comment]
so currently the implementation of phiv method in KrylovKit is the closest implementation comparing to this I can find, but KrylovKit works fine and gives the right result, still not sure what is different here. IMO the relative code is a bit convoluted here, so it is a bit hard to figure out for me since I'm not familiar with it...

**Comment by ChrisRackauckas** [comment]
you'll want to read through the old PRs that walk through all of it.

**Comment by Roger-luo** [comment]
the above bug somehow disappear in the latest version

```julia
cols = [1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 28, 28, 28, 28, 29, 29, 29, 29, 30, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 32, 32, 32, 32, 33, 33, 33, 33, 33, 34, 34, 34, 34, 34, 35, 35, 35, 35, 35, 35, 35, 36, 36, 36, 36, 36, 36, 36, 37, 37, 37, 37, 37, 37, 38, 38, 38, 38, 38, 38, 39, 39, 39, 39, 39, 39, 40, 40, 40, 40, 40, 40, 41, 41, 41, 41, 41, 42, 42, 42, 42, 42, 43, 43, 43, 43, 43, 43, 44, 44, 44, 44, 44, 45, 45, 45, 45, 46, 46, 46, 46, 46, 47, 47, 47, 47, 47, 48, 48, 48, 48, 48, 48, 48, 49, 49, 49, 49, 49, 49, 50, 50, 50, 50, 50, 51, 51, 51, 51, 51, 52, 52, 52, 52, 52, 53, 53, 53, 53, 53, 53, 54, 54, 54, 54, 54, 55, 55, 55, 55, 55]
rows = [2, 3, 4, 6, 9, 14, 22, 35, 1, 5, 7, 10, 15, 23, 36, 1, 8, 11, 16, 24, 37, 1, 5, 12, 17, 25, 38, 2, 4, 5, 13, 18, 26, 39, 1, 7, 8, 19, 27, 40, 2, 6, 7, 20, 28, 41, 3, 6, 8, 21, 29, 42, 1, 10, 11, 12, 30, 43, 2, 9, 10, 13, 31, 44, 3, 9, 11, 32, 45, 4, 9, 12, 13, 33, 46, 5, 10, 12, 13, 34, 47, 1, 15, 16, 17, 19, 48, 2, 14, 15, 18, 20, 49, 3, 14, 16, 21, 50, 4, 14, 17, 18, 51, 5, 15, 17, 18, 52, 6, 14, 19, 20, 21, 53, 7, 15, 19, 20, 54, 8, 16, 19, 21, 55, 1, 23, 24, 25, 27, 30, 2, 22, 23, 26, 28, 31, 3, 22, 24, 29, 32, 4, 22, 25, 26, 33, 5, 23, 25, 26, 34, 6, 22, 27, 28, 29, 7, 23, 27, 28, 8, 24, 27, 29, 9, 22, 30, 31, 32, 33, 10, 23, 30, 31, 34, 11, 24, 30, 32, 12, 25, 30, 33, 34, 13, 26, 31, 33, 34, 1, 36, 37, 38, 40, 43, 48, 2, 35, 36, 39, 41, 44, 49, 3, 35, 37, 42, 45, 50, 4, 35, 38, 39, 46, 51, 5, 36, 38, 39, 47, 52, 6, 35, 40, 41, 42, 53, 7, 36, 40, 41, 54, 8, 37, 40, 42, 55, 9, 35, 43, 44, 45, 46, 10, 36, 43, 44, 47, 11, 37, 43, 45, 12, 38, 43, 46, 47, 13, 39, 44, 46, 47, 14, 35, 48, 49, 50, 51, 53, 15, 36, 48, 49, 52, 54, 16, 37, 48, 50, 55, 17, 38, 48, 51, 52, 18, 39, 49, 51, 52, 19, 40, 48, 53, 54, 55, 20, 41, 49, 53, 54, 21, 42, 50, 53, 55]
vals = [12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0, 12.566370614359172, 12.566370614359172, 12.566370614359172, 12.566370614359172, 0.0]

H = sparse(rows, cols, vals)

t = 0.9; st = rand(ComplexF64, 55);

expv(-im*t, Matrix(H), st) ≈ exp(-im*t*Matrix(H)) * st
right = exp(-im*t*Matrix(H)) * st
expv_ans = expv(-im*t, Matrix(H), st)
default = expv_timestep(t, -im * H, st)
default_tol = expv_timestep(t, -im * H, st; m=30, adaptive=true, tol=1e-7)
large_krylov = expv_timestep(t, -im * H, st; m=30, adaptive=true, tol=1e-14)

norm(right - expv_ans) # 3.071110620453493
norm(right - default) # 0.14839172821643723
norm(right - default_tol) # 8.860098972853507e-10
norm(right - large_krylov) # 2.0944838484187024e-14
right ≈ large_krylov # true
right ≈ default_tol # true
```

I'm not sure why the default Krylov space size is only 10 tho
